name: chatgpt
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  velocity_x: ^3.6.0
  auto_size_text: ^3.0.0
  chat_gpt_sdk: ^1.0.2+4
  flutter_dotenv: ^5.0.2

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

