name: chatgpt
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter

  chat_gpt_sdk: ^1.0.2+4
  cloud_firestore: ^4.3.2
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  firebase_storage: ^11.0.11
  flutter_animate: ^3.1.0
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.0.0+1
  google_sign_in: ^5.4.4
  velocity_x: ^3.6.0
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - ".env"
    - "assets/svgs/."
