// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq-sAePzxD_AmdaqGwxsre-H19JtBhFgc',
    appId: '1:936117647518:web:210f81f5dd6fb83544e38f',
    messagingSenderId: '936117647518',
    projectId: 'openaibotflutter',
    authDomain: 'openaibotflutter.firebaseapp.com',
    storageBucket: 'openaibotflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe5rsA-CzEjbZT06zWJAmFAdje-73Luik',
    appId: '1:936117647518:android:ef355cd56acbdf0344e38f',
    messagingSenderId: '936117647518',
    projectId: 'openaibotflutter',
    storageBucket: 'openaibotflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2wfh2--gpeiXRJvmdcGfuoidio9tHktA',
    appId: '1:936117647518:ios:d4f0e71342dbd7be44e38f',
    messagingSenderId: '936117647518',
    projectId: 'openaibotflutter',
    storageBucket: 'openaibotflutter.appspot.com',
    iosClientId: '936117647518-rt8qo1dcd3eupo6ek1bcd5tb8pgusimo.apps.googleusercontent.com',
    iosBundleId: 'com.ritic.chatgpt.chatgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2wfh2--gpeiXRJvmdcGfuoidio9tHktA',
    appId: '1:936117647518:ios:d4f0e71342dbd7be44e38f',
    messagingSenderId: '936117647518',
    projectId: 'openaibotflutter',
    storageBucket: 'openaibotflutter.appspot.com',
    iosClientId: '936117647518-rt8qo1dcd3eupo6ek1bcd5tb8pgusimo.apps.googleusercontent.com',
    iosBundleId: 'com.ritic.chatgpt.chatgpt',
  );
}
